"""Add payment fields to Order

Revision ID: 005dd2116ed9
Revises: e02679935f60
Create Date: 2025-04-16 08:58:46.618161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005dd2116ed9'
down_revision = 'e02679935f60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('upi_transaction_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('payment_status')
        batch_op.drop_column('upi_transaction_id')
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
