"""Add notes field to Order

Revision ID: 01ef5c6470c0
Revises: 005dd2116ed9
Create Date: 2025-04-16 11:06:26.025091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01ef5c6470c0'
down_revision = '005dd2116ed9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
